### ISSUE TITLE
[QUESTION] - How many requests we can do per second?

### ISSUE THREAD

**Issue by lucasoares** [benjaminguinaudeau/tiktokr#30]
Hello.

After november and with CAPTCHA implementation my cookie verifyFp gets blocked and I have to change it or create a new one accessing the browser directly.

Did you ever tried to find out how many user_posts requests (for example) you can do before being blocked? Are you manually getting new cookie each time you are blocked?

Thanks

**Comment by favstats** [comment]
Hi Lucas! 

Have you tried waiting for a little or do you know for certain that your cookie is permanently blocked?

I've been using the same cookie the last couple of days without having to change it. My requests do occasionally get blocked but I just error handle them and try again in a few minutes, has worked for me without problems.

**Comment by hidayaa** [comment]
@RohanAlexander and I are wondering if you would mind letting me know what it looks like when you 'get blocked' - we'd just like to confirm that this is the issue and nothing else. Does it look like this?

![image](https://user-images.githubusercontent.com/36558370/101082192-11bf5980-3579-11eb-9534-38303b077c19.png)

Some background info, this seems to be a unique issue, all the other functions that I have tested out works (i.e user_posts &trends). I double check the issue by getting a new cookie & the code still does not run. I got a new cookie and it does not seem to be solving the problem.

Thanks :)

**Comment by benjaminguinaudeau** [comment]
Hi, 

This is one big issue with working on unofficial API. If the request is badly specified (for instance, wrong user agent), you get an empty body. If the request is actually blocked, you normally get a statusCode == 10000 (higher than 1000 if the query parameter is wrong, like a nonexisting user). 

I've been working on improving the error messages in the dev branch. Feel free to install this version, which may give you more accurate information about the error message.

**Comment by hidayaa** [comment]
Hi Benjamin, 

Sorry for the late response.  I tried the dplyr::gplimpse method you sent me but I'm still getting the error. 

See images below. 

Code: 
![image](https://user-images.githubusercontent.com/36558370/101525953-05ad1080-395a-11eb-96a6-b5139d6c13a0.png)

Output: 
![image](https://user-images.githubusercontent.com/36558370/101525977-0e054b80-395a-11eb-8314-6b6b38fa9f11.png)

Thanks in advance :)

**Comment by benjaminguinaudeau** [comment]
Hi, 

Sorry for the misunderstanding. `dplyr::glimpse()` only print a dataframe in a light way. 

In the meantime, we've merged the dev branch into the main. So, simply try to reinstall the package and let me know if that works.

**Comment by hidayaa** [comment]
Hey, 

I reinstalled and still no luck. I'm using a Mac if should that make a difference? 

Thanks for your help on this! Much appreciated!
